// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/plab1-home/CalmConcierge.tsx": () => import("../components/mockups/plab1-home/CalmConcierge.tsx"),
  "./components/mockups/plab1-home/ProgressDashboard.tsx": () => import("../components/mockups/plab1-home/ProgressDashboard.tsx"),
  "./components/mockups/plab1-home/QuickStartChips.tsx": () => import("../components/mockups/plab1-home/QuickStartChips.tsx")
};
